import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  MANUAL_SERVER_REQUESTS, NATIVE_SERVER_REQUESTS, PLATFORM_ONLY_SERVER_REQUESTS,
  SERVER_REQUEST_SUPPORT, THREAD_ITEM_TYPES, protocolSupportSummary,
} from '../public/protocol-support.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('archive support registry covers every current first-class Codex item disposition', () => {
  assert.equal(THREAD_ITEM_TYPES.length, 18);
  assert.equal(new Set(THREAD_ITEM_TYPES).size, THREAD_ITEM_TYPES.length);
  const app = fs.readFileSync(path.join(root, 'public/app.js'), 'utf8');
  for (const type of THREAD_ITEM_TYPES) assert.match(app, new RegExp(`case\\s*['\"]${type}['\"]`), `missing native renderer disposition for ${type}`);
});

test('composer keeps workspace selection in the primary new-thread flow and supports official image input', () => {
  const html = fs.readFileSync(path.join(root, 'public/index.html'), 'utf8');
  const app = fs.readFileSync(path.join(root, 'public/app.js'), 'utf8');
  const liveActivity = fs.readFileSync(path.join(root, 'public/live-activity.js'), 'utf8');
  const css = fs.readFileSync(path.join(root, 'public/styles.css'), 'utf8');
  const protocol = fs.readFileSync(path.join(root, 'public/protocol-support.js'), 'utf8');
  assert.doesNotMatch(html, /id="workspaceButton"/);
  assert.match(html, /id="attachButton"/);
  assert.match(html, /id="attachmentInput"[^>]+accept="image\//);
  assert.doesNotMatch(html, /id="capabilitiesButton"/);
  assert.doesNotMatch(html, /id="imagePasteHint"/);
  assert.doesNotMatch(html, /id="composerHint"/);
  assert.match(html, /id="capabilityCards"/);
  assert.match(app, /type:'image',url:/);
  assert.match(app, /function handleClipboardPaste/);
  assert.match(app, /addEventListener\('paste',handleClipboardPaste\)/);
  assert.match(app, /threadSelectionSerial/);
  assert.match(app, /function loadMethodSchema/);
  assert.match(app, /mcpServerStatus\/list/);
  assert.match(app, /plugin\/list/);
  assert.match(app, /config\/read/);
  assert.match(app, /config\/batchWrite/);
  assert.match(app, /model_reasoning_effort/);
  assert.match(html, /id="composerMode"/);
  assert.match(html, /id="contextIndicator"/);
  assert.match(html, /id="compactThread"/);
  assert.match(html, /id="contextUsage"/);
  assert.match(html, /id="contextUsageFill"/);
  assert.match(html, /id="contextUsageRemainingValue"/);
  assert.match(html, /id="fullHistoryButton"/);
  assert.match(html, /id="historySearchBar"/);
  assert.match(html, /id="historySearchInput"/);
  assert.match(html, /id="officialPlanDock"/);
  assert.match(html, /id="autoScrollToggle"/);
  assert.match(html, /id="deliveryStatus"/);
  assert.match(app, /turn\/steer/);
  assert.match(app, /clientUserMessageId/);
  assert.match(app, /const request=rpc\('turn\/start'/);
  assert.match(app, /clearComposer\(\);const r=await request/);
  assert.match(app, /restoreComposerFromAttempt/);
  assert.match(app, /if\(localWebTurnActive\(\)\)\{await steerPrompt/);
  assert.match(app, /isUncertainSendError/);
  assert.match(app, /markWebTurnStartUnknown/);
  assert.match(app, /reconcilePendingSubmission/);
  assert.match(app, /DELIVERY_STORAGE_KEY/);
  assert.match(app, /knownTurnIds:\[\.\.\.\(attempt\?\.knownTurnIds\|\|\[\]\)/);
  assert.match(app, /pendingTurnStartMatches/);
  assert.match(app, /send\.dataset\.deliveryPending/);
  assert.match(app, /removeDuplicateOptimisticUser/);
  assert.match(app, /turnClockTimer/);
  assert.match(app, /renderLiveTurnClock/);
  assert.match(app, /setInterval\(\(\)=>renderLiveTurnClock\(\),1_000\)/);
  assert.match(app, /liveTurnItems/);
  assert.match(app, /turn\/steer.*clientUserMessageId/);
  assert.match(app, /mergeLiveItemsIntoTurn/);
  assert.match(app, /thread\/compact\/start/);
  assert.match(app, /thread\/compacted/);
  assert.match(app, /thread\/tokenUsage\/updated/);
  assert.match(app, /modelContextWindow/);
  assert.match(app, /contextUsageSnapshot/);
  assert.match(app, /tokenUsageThreadId/);
  assert.match(app, /function createWorkGroup/);
  assert.match(app, /function showContextCompaction/);
  assert.match(app, /function preserveLiveTimeline/);
  assert.match(app, /function removeIgnoredProtocolEvents/);
  assert.match(app, /threadCache:new Map/);
  assert.match(app, /function cachedThreadResponse/);
  assert.match(app, /function renderHistoryBatches/);
  assert.match(app, /function showThreadLoading/);
  assert.match(app, /function renderPendingWorkItems/);
  assert.match(app, /String\(id\)===String\(state\.currentThread\.id\)/);
  assert.match(app, /requestIdleCallback/);
  assert.match(app, /function readThreadForUi/);
  assert.match(app, /function isActiveOfficialStatus/);
  assert.match(app, /state\.threadReadInFlight/);
  assert.match(app, /new AbortController\(\)/);
  assert.match(app, /historyInsertPoint\(timeline,olderControl\)/);
  assert.match(app, /olderControl\.nextSibling/);
  assert.match(app, /const QUICK_HISTORY_PAGE_SIZE=10/);
  assert.match(app, /const FULL_HISTORY_PAGE_SIZE=10/);
  assert.match(app, /if\(!state\.fullHistoryMode\|\|!pager\?\.hasMore\)return/);
  assert.match(app, /thread\/turns\/list/);
  assert.match(app, /itemsView:'summary'/);
  assert.match(app, /thread\/items\/list/);
  assert.match(app, /HISTORY_ITEM_PAGE_SIZE/);
  const pagedHistory = app.slice(app.indexOf('async function readOfficialPagedThread'), app.indexOf('const readThreadForUiBeforeOfficialPaging'));
  assert.match(pagedHistory, /itemsView:'summary'/);
  assert.doesNotMatch(pagedHistory, /itemsView:'full'/);
  assert.match(app, /itemsView:'full'/);
  assert.match(app, /QUICK_HISTORY_PAGE_SIZE/);
  assert.match(app, /FULL_HISTORY_PAGE_SIZE/);
  assert.match(app, /history-older-control/);
  assert.match(app, /fullHistoryMode/);
  assert.match(app, /turnDuration=turn=>/);
  assert.match(app, /durationMs/);
  assert.match(app, /historySearchQuery/);
  assert.match(app, /Official search found \{count\} thread sections/);
  assert.match(app, /thread\/searchOccurrences/);
  assert.match(app, /OFFICIAL_SEARCH_PAGE_SIZE/);
  assert.match(app, /function officialHistoryPage/);
  assert.match(app, /running\?tr\('workInProgress'\)/);
  assert.match(app, /contextUsageWaiting/);
  assert.match(app, /AUTO_SCROLL_STORAGE_KEY/);
  assert.match(app, /scrollBottomBeforeAutoScroll/);
  assert.match(app, /renderOfficialPlanBottomCard/);
  assert.match(app, /officialPlanExpandedTurnId/);
  assert.match(app, /officialActiveTurnId/);
  assert.match(app, /officialThreadActive/);
  assert.match(app, /classifyOfficialActivity/);
  assert.match(app, /control:\{webWriteEnabled:true/);
  assert.doesNotMatch(app, /desktopWriteProtection|controlDesktopGuardEnabled|桌面占用保护|Desktop ownership guard/);
  assert.doesNotMatch(html, /desktopGuardToggle|desktopGuardState|桌面占用保护/);
  assert.match(app, /eventReconnectWatchdog/);
  assert.match(css, /\.history-older-control/);
  assert.match(css, /\.history-older-control\.with-search/);
  assert.match(css, /\.history-page-marker/);
  assert.match(css, /\.history-items-placeholder/);
  assert.match(css, /\.official-plan-dock/);
  assert.match(css, /\.history-search/);
  assert.match(css, /\.turn-header-detail\{display:inline/);
  assert.match(app, /function approvalInfo/);
  assert.match(app, /approvalCommandTitle/);
  assert.match(app, /approvalTechnical/);
  assert.match(app, /function syncContextCompactionLifecycle/);
  assert.match(app, /m==='turn\/diff\/updated'/);
  assert.match(app, /turn\/moderationMetadata/);
  assert.match(app, /m==='turn\/plan\/updated'/);
  assert.match(app, /function upsertOfficialPlan/);
  assert.match(app, /officialSource/);
  assert.match(app, /renderOfficialPlanInteractive/);
  assert.match(app, /mobilePlanInteraction/);
  assert.match(app, /closeOpenOfficialPlans/);
  assert.match(app, /Dynamic Tool Host is not configured for/);
  assert.match(app, /else if\(r\.method==='item\/tool\/call'\)\{if\(state\.meta\?\.capabilities\?\.dynamicToolHost\?\.enabled===true\)/);
  assert.match(app, /LAST_THREAD_KEY/);
  assert.match(app, /function restoreLastThread/);
  assert.match(app, /function adoptPendingTurnBlock/);
  assert.match(app, /data-pending-turn/);
  assert.match(app, /await restoreLastThread\(\)/);
  assert.match(app, /runtimeBootId/);
  assert.match(app, /startRuntimeRecoveryMonitor/);
  assert.match(app, /probeRuntimeRecovery/);
  assert.match(app, /turnReconcileTimer/);
  assert.match(app, /SEALED_TERMINAL_TURN_METHODS/);
  assert.match(app, /state\.activeTurnId.*historyLoaded/);
  assert.match(liveActivity, /active\.length!==1/);
  assert.match(liveActivity, /thread\/status\/changed/);
  assert.match(liveActivity, /turn\/started/);
  assert.match(liveActivity, /turn\/completed/);
  assert.match(app, /timeline\.insertBefore\(button,searchBar\.nextSibling\)/);
  assert.match(app, /thread\/archive/);
  assert.match(app, /thread\/unarchive/);
  assert.match(app, /thread\/name\/set/);
  assert.match(app, /thread\/delete/);
  assert.match(app, /function invalidateThreadHistory/);
  assert.match(app, /function runThreadOperation/);
  assert.match(app, /threadOperationBusy/);
  assert.match(app, /readThreadForUi\(id,\{force,signal:controller\.signal\}\)/);
  assert.doesNotMatch(app, /if\(!force\)await ensureThreadLoaded/);
  assert.match(protocol, /turn\/diff\/updated/);
  assert.match(app, /kind==='ignore'/);
  assert.match(css, /grid-template-columns:minmax\(0,1fr\) auto/);
  assert.match(css, /@media\(max-width:480px\)\{\s*\.composer-toolbar\{grid-template-columns:minmax\(0,1fr\)/);
  assert.match(css, /container-type:inline-size/);
  assert.match(css, /@container \(max-width:720px\)/);
  assert.match(css, /\.attach-button\{writing-mode:horizontal-tb;white-space:nowrap!important/);
  assert.match(app, /const incomingIds=new Set/);
  assert.match(app, /pending=visibleBlocks\.some/);
  assert.match(css, /\.topbar\{min-width:0;max-width:100%;overflow:hidden\}/);
  assert.match(css, /\.top-actions #openProtocolTop\{display:none\}/);
  assert.match(css, /\.approval-card-head/);
  assert.match(css, /\.approval-technical/);
});

test('all declared ServerRequest methods have one explicit trust/UI disposition', () => {
  const entries = Object.entries(SERVER_REQUEST_SUPPORT);
  assert.equal(entries.length, 11);
  assert.equal(new Set(entries.map(([method]) => method)).size, entries.length);
  assert.deepEqual(new Set([...NATIVE_SERVER_REQUESTS, ...MANUAL_SERVER_REQUESTS, ...PLATFORM_ONLY_SERVER_REQUESTS]), new Set(entries.map(([method]) => method)));
  assert.equal(PLATFORM_ONLY_SERVER_REQUESTS.includes('attestation/generate'), true);
  assert.equal(PLATFORM_ONLY_SERVER_REQUESTS.includes('account/chatgptAuthTokens/refresh'), true);
  assert.equal(SERVER_REQUEST_SUPPORT['currentTime/read'], 'native-experimental-host');
  assert.equal(SERVER_REQUEST_SUPPORT['item/tool/call'], 'native-tool-host');
});

test('published support summary advertises only implemented archive hosts', () => {
  const summary = protocolSupportSummary();
  assert.equal(summary.threadItemTypes, 18);
  assert.equal(summary.serverRequests, 11);
  assert.equal(summary.openaiForm, true);
  assert.equal(summary.mcpAppsHost, true);
  assert.equal(summary.dynamicToolHost, true);
  assert.equal(summary.currentTimeHost, true);
  assert.equal(summary.experimentalProtocolSeal, true);
});

test('runtime server advertises the implemented MCP Apps profile and gates Dynamic Tools experimentally', () => {
  const server = fs.readFileSync(path.join(root, 'src/server.mjs'), 'utf8');
  const config = fs.readFileSync(path.join(root, 'src/config.mjs'), 'utf8');
  assert.match(server, /MCP_APPS_EXTENSION/);
  assert.match(server, /mimeTypes:\s*\[MCP_APPS_MIME\]/);
  assert.match(server, /TURN_START_DEDUPE_TTL_MS/);
  assert.match(server, /method !== 'turn\/start' && method !== 'turn\/steer'/);
  assert.match(server, /return existing\.promise/);
  assert.match(server, /mcpAppsDoubleIframeSandbox:\s*true/);
  assert.match(server, /CWEB_DYNAMIC_TOOLS_FILE requires CWEB_EXPERIMENTAL=1/);
  assert.match(server, /properties\?\.dynamicTools/);
  assert.match(server, /message\.method === 'currentTime\/read'/);
  assert.match(server, /function rejectDynamicToolRequest/);
  assert.match(server, /dynamic-tool-host-unconfigured/);
  assert.match(server, /if \(configured\) pushEvent\('serverRequestUnsupported'/);
  assert.match(server, /HUMAN_IGNORED_NOTIFICATION_METHODS/);
  assert.match(server, /turn\/diff\/updated.*turn\/moderationMetadata/);
  assert.match(config, /\['turn\/diff\/updated', 'turn\/moderationMetadata', \.\.\.list\('CWEB_NOTIFICATION_OPT_OUT'\)\]/);
  assert.match(server, /function compactRpcError/);
  assert.doesNotMatch(server, /rpc: error\.rpc/);
  assert.match(server, /new SessionStore\(12 \* 60 \* 60 \* 1000, 256, config\.token\)/);
  assert.match(server, /runtimeBootId/);
  assert.match(server, /runtimeStartedAt/);
  assert.match(server, /no rollout found for thread id/);
  assert.match(server, /pushEvent\('webRestarting'/);
  assert.match(server, /transport: config\.codexTransport/);
  assert.match(server, /persistentOfficialAppServer/);
  assert.match(config, /CWEB_CODEX_TRANSPORT/);
  assert.match(config, /CWEB_CODEX_SERVER_URL/);
});

test('Codex child transport failures have an explicit containment path', () => {
  const client = fs.readFileSync(path.join(root, 'src/codex-client.mjs'), 'utf8');
  assert.match(client, /child\.stdin\.on\('error', failTransport\)/);
  assert.match(client, /emit\('transportError'/);
  assert.match(client, /try \{ child\.stdin\.write\(data\); \}/);
  assert.match(client, /WebSocket backpressure limit reached/);
  assert.match(client, /WebSocket message larger than/);
});

test('MCP Apps host bridge covers stable server tool/resource proxy surfaces', () => {
  const host = fs.readFileSync(path.join(root, 'public/mcp-app-host.js'), 'utf8');
  for (const method of ['ui/initialize', 'tools/list', 'tools/call', 'resources/list', 'resources/templates/list', 'resources/read', 'ui/open-link', 'ui/request-display-mode']) {
    assert.match(host, new RegExp(method.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
  assert.match(host, /originCallId/);
  assert.match(host, /toolVisibleToApp/);
  assert.match(host, /mcpServer\/resource\/read/);
  assert.match(host, /mcpServer\/tool\/call/);
});

test('legacy and v2 approval decision vocabularies remain separate', () => {
  const app = fs.readFileSync(path.join(root, 'public/app.js'), 'utf8');
  for (const decision of ['approved', 'approved_for_session', 'accept', 'acceptForSession']) assert.match(app, new RegExp(`decision\\s*:\\s*['\"]${decision}['\"]`), decision);
  assert.match(app, /action\s*:\s*['\"]accept['\"]\s*,\s*content\s*:/);
  assert.match(app, /_meta\s*:\s*null/);
});
